### ISSUE TITLE
Select2 Value not empty after successful submit

### ISSUE THREAD

**Issue by thebarty** [aldeed/meteor-autoform-select2#47] opened 2015-09-24 13:14 UTC
Hi guys,

there seems to be an error: The values in the select2 field **still remain** and are **NOT resetted** after a successful submit.

I am using this with a quickform.

This is how my schema looks like:

```
  scoopSelectionIds: {
    type: [String],  // =Array
    optional: false,
    autoform: {
      type: 'select2',
      afFieldInput: {
        multiple: true
      },
      options: function () {
        return Scoops.find().map(function (c) {
          return {label: c.name, value: c._id};
        });
      },
    },
  },
```

**Comment by bipin244** [comment] 2015-10-14 04:29
Same Problem !!!!!!!!!!!!!

**Comment by BioMechanico** [comment] 2015-11-13 00:41
I have this same problem, I think I know why but I don't know how to fix it.  When you remove values from select2 instead of returning an empty array it returns an empty string. Since the type is \[String\] (as it should be for multi-select Select2) we're getting an error.  I've tried adding an autovalue that will change an empty string to an empty array but it doesn't work:

```javascript
  autoValue: function() {
    if ((this.isSet||this.isInsert) && this.value=="" && typeof(this.value)=="string") return []
  },
```

anyone else have any luck?

**Comment by thearabbit** [comment] 2015-11-18 06:42
I have the same problem for this.
And then if the form is error (validation) it is clear the select2.

**Comment by steedos** [comment] 2015-11-24 03:13
+1

When calll AutoForm.resetForm(formId), the previous selected value still show on form.

**Comment by proft** [comment] 2015-12-18 15:28
+1

**Comment by ashishgupta2** [comment] 2016-03-01 11:20
+1

We are having the same problem. Anyone have any luck with this?

**Comment by nabiltntn** [comment] 2016-09-12 23:42
+1

**Comment by jkd65** [comment] 2016-10-09 00:52
Same issue, hope someone has a solution?

**Comment by aldeed** [comment] 2017-03-26 15:00
Closing as duplicate of #37 (best solution is to clear it yourself using select2 API in a `form reset` event listener.

**Closed by aldeed** 2017-03-26 15:00 UTC
